"""
tagi_lstm.py
============
TAGI-LSTM with a PyTorch-style API, built on the autograd-style Gaussian
inference engine (tagi_autograd.py), following the TAGI-LSTM paper
(Vuong et al., "Coupling LSTM Neural Networks and State-Space Models
through Analytically Tractable Inference").

API mirrors torch.nn:

    cell = LSTMCell(input_size, hidden_size)      # ~ nn.LSTMCell
    h1, c1 = cell(x_t, (h0, c0))                  # __call__ -> forward

    rnn = LSTM(input_size, hidden_size, num_layers=2)   # stacked, ~ nn.LSTM
    out, hx = rnn(x_t, hx)

    class Net(Module):                            # user model: forward only
        def __init__(self):
            self.lstm = LSTM(5, 32)
            self.fc = Linear(32, 1)
        def forward(self, x, hx=None):
            h, hx = self.lstm(x, hx)
            return self.fc(h), hx

Training loop (compare with a PyTorch truncated-BPTT loop):

    PyTorch                                TAGI
    -------------------------------        -------------------------------
    out, hx = net(x_t, hx)                 out, hx = net(tensor(x_t), hx)
    loss = mse(out, y_t)                   #
    loss.backward()                        out.observe(y_t, var_v)
    optimizer.step()                       #   (inference IS the update)
    hx = tuple(h.detach() ...)             hx = detach_state(hx)

`observe` replaces loss.backward()+optimizer.step(): it conditions every
hidden state and parameter on y_t analytically.  `detach()` carries the
POSTERIOR filtered state h_t|t, c_t|t into the next step's graph as a
fresh leaf -- the filtering recursion of the paper (Sec. 4.1.1-4.1.2).

Parameters follow torch.nn.LSTMCell's fused layout:
    weight_ih : (4*hidden_size, input_size)     gate order  i | f | g | o
    weight_hh : (4*hidden_size, hidden_size)    (g is the candidate c~)
    bias_ih, bias_hh : (4*hidden_size,)
The fused pre-activations are split with the engine's `chunk` op, whose
backward is an exact scatter (gain 1).  Note the paper writes the gates in
the order f, i, o, c~ (Eq. 1a-1d); the math is identical, only the row
layout differs.  Everything is Gaussian with diagonal covariance, and the
backward inference through the gates is generated automatically by the
engine (see test_tagi.py: it reproduces the paper's Appendix C/D
covariances to machine precision).

Run:  python tagi_lstm.py
"""

from __future__ import annotations

import numpy as np
from tagi_autograd import (
    Linear,
    Module,
    Parameter,
    add,
    chunk,
    linear,
    mul,
    sigmoid,
    tanh,
    tensor,
)


# =============================================================================
#  LSTMCell -- analogue of torch.nn.LSTMCell
# =============================================================================
class LSTMCell(Module):
    """
    A TAGI-LSTM cell.  forward(input, hx=None) -> (h_1, c_1),
    with hx = (h_0, c_0) defaulting to a zero-mean, small-variance prior.

    The forward pass is the paper's Eq. 1a-1f written with the engine's
    Gaussian graph ops; all inference code is generated by the engine by
    composing its four local rules (see tagi_autograd module docstring)
    along the cell's wiring.  The resulting CHAINS, for a packet
    Delta(h) arriving at h_t (intermediate variances cancel):

      target        route                composite gain x Delta(h)
      ------------  -------------------  ---------------------------------
      o             h->o                 var(o)*mu_tc / var(h)
      c             h->tanh(c)->c        J_c*var(c)*mu_o / var(h)
                                         [= paper cov(C,H), Sec. 4.1.2]
      c_prev        ..c->f*c_prev->      var(c_prev)*mu_f*[J_c*mu_o]/var(h)
                                         [= paper App. D.2]
      f             ..c->f*c_prev->f     var(f)*mu_cprev*[J_c*mu_o]/var(h)
      i, g          ..c->i*g->           symmetric (partner's mu)
      W_f, b_f      ..f->z_f->z_ih->     var(th)*mu_x*J_f*mu_cprev
                                           *J_c*mu_o / var(h)
                                         [= paper cov(W^f,H), App. C.2]
      U_f           ..f->z_f->z_hh->     same with mu_hprev in place of mu_x
      W_o,U_o,b_o   h->o->z_o->          var(th)*mu_in*J_o*mu_tc / var(h)
                                         (short chain: no cell-state factors)
      h_prev        4 routes (one per    SUM of the four chain products
                    gate), summed        [App. C.1/D.1 structure]
      x             4 routes via W_g     dies if var(x) = 0

    Reading rule: one var(target), then one factor per hop crossed --
    mu of the GMA partner for each product, J for each activation --
    all over var(h).  Every gate parameter ends with the identical
    linear rule; chains differ only in the packet delivered to it.
    Call tagi_autograd.set_trace(True) to watch these chains execute.

    Node names inside the graph match this table (z_gates, z_i/z_f/z_g/z_o,
    i/f/g/o, f*c_prev, i*g, c, tanh(c), h) so traces are readable.
    """

    def __init__(
        self,
        input_size: int,
        hidden_size: int,
        bias: bool = True,
        rng=None,
        gain: float = 1.0,
    ):
        rng = rng or np.random.default_rng()
        self.input_size, self.hidden_size = input_size, hidden_size
        s = gain / np.sqrt(input_size + hidden_size)
        H4 = 4 * hidden_size

        def par(shape, name):
            return Parameter(
                rng.normal(0.0, s, shape), np.full(shape, s**2), name=name
            )

        self.weight_ih = par((H4, input_size), "weight_ih")
        self.weight_hh = par((H4, hidden_size), "weight_hh")
        if bias:
            self.bias_ih = Parameter(
                np.zeros(H4), np.full(H4, s**2), name="bias_ih"
            )
            self.bias_hh = Parameter(
                np.zeros(H4), np.full(H4, s**2), name="bias_hh"
            )
        else:
            self.bias_ih = self.bias_hh = None

    def _default_state(self, var0: float = 1e-2):
        z = np.zeros(self.hidden_size)
        return (tensor(z, var0, name="h0"), tensor(z, var0, name="c0"))

    def forward(self, input, hx=None):
        h_prev, c_prev = hx if hx is not None else self._default_state()

        # fused gate pre-activations:  W_ih x + b_ih + W_hh h + b_hh
        z_ih = linear(input, self.weight_ih, self.bias_ih).named("z_ih")
        z_hh = linear(h_prev, self.weight_hh, self.bias_hh).named("z_hh")
        gates = add(z_ih, z_hh).named("z_gates")
        z_i, z_f, z_g, z_o = chunk(gates, 4, name="z")  # torch order i|f|g|o
        z_i.named("z_i")
        z_f.named("z_f")
        z_g.named("z_g")
        z_o.named("z_o")

        i = sigmoid(z_i).named("i")  # input gate
        f = sigmoid(z_f).named("f")  # forget gate     (1a-1d)
        g = tanh(z_g).named("g")  # candidate  c~
        o = sigmoid(z_o).named("o")  # output gate

        p = mul(f, c_prev).named("f*c_prev")
        q = mul(i, g).named("i*g")
        c = add(p, q).named("c")  # (1e) GMA + addition
        tc = tanh(c).named("tanh(c)")
        h = mul(o, tc).named("h")  # (1f)

        # retain posterior moments so detach() after observe() carries the
        # FILTERED state h_t|t, c_t|t into the next step (paper Sec. 4.1.2)
        return h.retain(), c.retain()


# =============================================================================
#  LSTM -- stacked cells, analogue of torch.nn.LSTM
# =============================================================================
class LSTM(Module):
    """
    Stacked TAGI-LSTM (paper Fig. 2b).  forward(input, hx=None) ->
    (output, hx_new) where output is the top layer's h and hx is a list of
    (h, c) per layer.

    Unlike torch.nn.LSTM this steps ONE time point per call: TAGI
    conditions online -- each observation must update the states before
    the next step's forward -- so the time loop lives in user code, as in
    a truncated-BPTT training loop with nn.LSTMCell.
    """

    def __init__(
        self,
        input_size: int,
        hidden_size: int,
        num_layers: int = 1,
        bias: bool = True,
        rng=None,
    ):
        rng = rng or np.random.default_rng()
        self.cells = [
            LSTMCell(
                input_size if l == 0 else hidden_size,
                hidden_size,
                bias=bias,
                rng=rng,
            )
            for l in range(num_layers)
        ]

    def forward(self, input, hx=None):
        if hx is None:
            hx = [None] * len(self.cells)
        out, new_hx = input, []
        for cell, state in zip(self.cells, hx):
            h, c = cell(out, state)
            new_hx.append((h, c))
            out = h
        return out, new_hx


def detach_state(hx):
    """PyTorch-style state carrying: hx = detach_state(hx) after observe().
    Uses the POSTERIOR (filtered) moments where a backward sweep filled
    them, the prior moments otherwise (e.g. pure forecasting)."""
    return [(h.detach(), c.detach()) for h, c in hx]


# =============================================================================
#  Running example: synthetic weekly series (paper, Section 5.1, Eq. 19a)
# =============================================================================
if __name__ == "__main__":
    rng = np.random.default_rng(7)

    # ------------------------------ data ------------------------------
    P1, P2 = 365.22 / 7, 365.22 / 7 / 4  # yearly + quarterly (weeks)
    T_total, T_train = 520, 468  # 10 years, train on 9
    t_axis = np.arange(T_total)

    def ground_truth(t):
        return np.sin(2 * np.pi * t / P1) + 0.5 * np.sin(2 * np.pi * t / P2)

    sigma_v = 0.2
    y = ground_truth(t_axis) + rng.normal(0.0, sigma_v, T_total)

    def time_features(t):
        return np.array(
            [
                np.sin(2 * np.pi * t / P1),
                np.cos(2 * np.pi * t / P1),
                np.sin(2 * np.pi * t / P2),
                np.cos(2 * np.pi * t / P2),
            ]
        )

    # covariates: [lagged y, time features]
    covs = np.array(
        [
            np.concatenate([[y[t - 1]], time_features(t)])
            for t in range(1, T_train)
        ]
    )
    targets = y[1:T_train]

    # --------------------------- the model ----------------------------
    class Net(Module):
        def __init__(self, rng):
            self.lstm = LSTM(
                input_size=5, hidden_size=32, num_layers=1, rng=rng
            )
            self.fc = Linear(32, 1, rng=rng)

        def forward(self, x, hx=None):
            h, hx = self.lstm(x, hx)
            return self.fc(h), hx

    net = Net(np.random.default_rng(1))
    var_v = sigma_v**2

    # ------------------ training loop, PyTorch style ------------------
    for epoch in range(25):
        hx, log_lik = None, 0.0
        for t in range(len(targets)):
            out, hx = net(tensor(covs[t]), hx)  # forward
            var_y = out.var[0] + var_v
            log_lik += (
                -0.5 * np.log(2 * np.pi * var_y)
                - 0.5 * (targets[t] - out.mu[0]) ** 2 / var_y
            )
            out.observe([targets[t]], var_v=var_v)  # "backward + step"
            hx = detach_state(hx)  # carry filtered state
        if epoch % 5 == 0 or epoch == 24:
            print(
                f"epoch {epoch:3d} | avg log-likelihood = "
                f"{log_lik / len(targets):8.4f}"
            )

    # -------- recursive 52-step forecast, feeding back (mu, var) ------
    n_test = T_total - T_train
    lag_mu, lag_var = y[T_train - 1], 0.0
    mu_f, var_f = [], []
    for k in range(n_test):
        feats = time_features(T_train + k)
        x = tensor(
            np.concatenate([[lag_mu], feats]),
            np.concatenate([[lag_var], np.zeros(4)]),
        )
        out, hx = net(x, hx)  # forward only
        mu_f.append(out.mu[0])
        var_f.append(out.var[0])
        hx = detach_state(hx)  # prior state (no obs)
        lag_mu, lag_var = out.mu[0], out.var[0]  # uncertainty feeds back
    mu_f, var_f = np.array(mu_f), np.array(var_f)
    sd_f = np.sqrt(var_f + var_v)

    truth_test = ground_truth(t_axis[T_train:])
    rmse = np.sqrt(np.mean((mu_f - truth_test) ** 2))
    cover = np.mean(np.abs(truth_test - mu_f) <= sd_f)
    print(f"\n52-week recursive forecast:  RMSE vs ground truth = {rmse:.4f}")
    print(f"                             +/-1 sigma coverage    = {cover:.2%}")

    # ------------------------------ plot ------------------------------
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 4.5))
        ax.plot(
            t_axis[:T_train],
            y[:T_train],
            "k.",
            ms=3,
            alpha=0.4,
            label="training data",
        )
        ax.plot(t_axis, ground_truth(t_axis), "r", lw=1, label="ground truth")
        ax.plot(t_axis[T_train:], mu_f, "b", lw=1.5, label="TAGI-LSTM forecast")
        ax.fill_between(
            t_axis[T_train:],
            mu_f - sd_f,
            mu_f + sd_f,
            color="b",
            alpha=0.25,
            label=r"$\pm\sigma$",
        )
        ax.axvline(T_train, color="gray", ls=":")
        ax.set_xlabel("week")
        ax.set_ylabel("y")
        ax.set_title(
            "TAGI-LSTM (PyTorch-style API): analytical filtering + "
            "recursive forecast"
        )
        ax.legend(ncol=4, fontsize=9)
        fig.tight_layout()
        fig.savefig("tagi_lstm_demo.png", dpi=130)
        print("plot saved to tagi_lstm_demo.png")
    except ImportError:
        pass
